[package]
name = "lt8722"
version = "0.1.0"
edition = "2024"

[dependencies]
bilge = "0.3.0"
crc = "3.3.0"
defmt = "1.0.1"
embedded-hal = "1.0.0"
paste = "1.0.15"

[dev-dependencies]
embedded-hal-mock = "0.11.1"
